version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.4
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - 8123:8123
      - 9000:9000

  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U uptrace -d uptrace']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  uptrace:
    image: 'uptrace/uptrace:1.5.2'
    restart: on-failure
    volumes:
      - uptrace_data:/var/lib/uptrace
      - ./uptrace.yaml:/etc/uptrace/uptrace.yml
    ports:
      - 14317:14317
      - 14318:14318
    depends_on:
      clickhouse:
        condition: service_healthy

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317
    depends_on:
      - uptrace
      - clickhouse

volumes:
  uptrace_data:
    driver: local
  clickhouse_data:
    driver: local
  postgres_data:
    driver: local
